census/survey/urls.py
from django.urls import path
from . import views 


app_name = 'survey'

urlpatterns = [
	path('', views.redirect_to_survey, name='survey_redirect'),
	path('pre', views.pre_survey, name='pre_survey'),
	path('auth', views.auth_survey, name='survey_auth'),
	path('form', views.survey_form, name='survey_form'),
	path('thanks', views.post_survey, name='post_survey'),
	path('results', views.results, name='results'),
	path('api/chart/data', views.ChartData.as_view())
]

census/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('census.survey.urls')),
    path('', include('census.landing.urls')),
]

templates/base/_nav.html
<!doctype html>
<nav class='navbar navbar-default'>
	<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-brand-custom" href="#"> r/kpop demo census </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    	<ul class='nav navbar-nav'>
    		<li><a href="{% url 'survey:survey_redirect' %}"> Survey </a></li>
			<li><a href="{% url 'survey:results' %}"> Results </a></li>
		</ul>
		<ul class='nav navbar-nav navbar-right'>
			<li><a href="https://www.reddit.com/r/kpop">r/kpop</a></li>
			<li><a href="https://www.reddit.com/r/kpoppers">r/kpoppers</a></li>
			<li><a href="https://www.reddit.com/r/kpophelp/">r/kpophelp</a></li>
		</ul>
	</div>
</nav>

templates/base/base.html
<!doctype html>
{% load static from staticfiles %}

<!-- This is a Bootstrap4 starter template -->
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap3 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
    <!-- bootstrap-select CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "base/css/custom.css" %}">
  
    <title> Census demo </title>
  </head>


  <body class='body-custom'>
    <header>
      {% include 'base/_nav.html' %}
    </header>
    <main>
      {% block main_block %}
        
        <!-- MAIN_BLOCK -->

      {% endblock %}
    </main>
    <footer></footer>


    <!-- Optional JavaScript -->

    <!-- 1. jQuery, 2. Popper.js, 3. Bootstrap3 JS, 4. bootstrap-select, 5. Custom JS  -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>

    <!-- Latest minified Chart.js 2.7.2 --> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    
    <!-- Document onload scripts (e.g. bootstrap-select options) -->
    <script src="{% static "base/js/custom.js" %}"></script> 

    
    {% block script_block %} 
    {% endblock %} 
   
  </body>
</html>